import = ["/home/adelplace/.config/alacritty/catppuccin/catppuccin-mocha.yml"]

[font]
size = 13

[font.bold]
family = "Source Code Pro"
style = "Bold"

[font.bold_italic]
family = "Source Code Pro"
style = "Bold Italic"

[font.italic]
family = "Source Code Pro"
style = "Italic"

[font.normal]
family = "Source Code Pro"
style = "Regular"

[window]
opacity = 0.8

[window.padding]
x = 10
y = 10
